######################## default configuration ####################
baseURL = "https://peteletricaufba.github.io/"
title = "Site de teste do PET"
theme = "bigspring"
defaultContentLanguage = "br"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

# added by taffarel55
publishDir = "docs"