# main menu
[[main]]
name = "PÃ¡gina Inicial"
url = "/"
weight = 1

[[main]]
name = "Corrente Alternativa"
url = "blog"
weight = 2

[[main]]
name = "Atividades"
url = "atividades"
weight = 3

[[main]]
name = "Minicursos"
url = "minicurso"
weight = 4

[[main]]
name = "Time"
url = "time"
weight = 5

# footer menu left
[[footer_left]]
name = "Contato"
url = "#"

[[footer_left]]
name = "Quick Start"
url = "#"

[[footer_left]]
name = "Pricing"
url = "pricing"


# footer menu middle
[[footer_middle]]
name = "Pricing"
url = "pricing"

[[footer_middle]]
name = "Platform"
url = "#"

[[footer_middle]]
name = "Features"
url = "#"

# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"

[[footer_right]]
name = "FAQ"
url = "faq"